---

- name: Install Influxdata repo
  yum_repository:
    name: influxdata-el7
    baseurl: "{{ influxdata_repo }}"
    description: Influxdata
    gpgkey: https://repos.influxdata.com/influxdata-archive_compat.key

- name: Install InfluxDB
  yum:
    name: influxdb
    state: present

- name: Create InfluxDB config file from template
  template:
    src: influxdb.conf.j2
    dest: '/etc/influxdb/influxdb.conf'
    backup: "yes"

- name: Create a directory if it does not exist
  file:
    path: /trinity/local/var/lib/influxdb/
    state: directory
    mode: '0755'
    owner: influxdb
    group: influxdb

- name: Enable and start InfluxDB
  systemd:
    name: influxdb
    state: started
    enabled: "yes"
  when: not ha|default(False)

- name: Disable and stop InfluxDB
  systemd:
    name: influxdb
    state: stopped
    enabled: "no"
  when: ha|default(False)

- name: Install python2-pip
  yum:
    name: python2-pip
    state: present

- name: Install influxdb pip
  pip:
    name: influxdb
    state: present

- name: Configure influxdb database
  influxdb_database:
    hostname: "{{ influxdb_server }}"
    database_name: "{{ item }}"
    state: present
  with_items:
    - telegraf
    - slurm
  failed_when: false

- name: Retention
  influxdb_retention_policy:
    hostname: "{{ influxdb_server }}"
    database_name: telegraf
    policy_name: 2months
    duration: 60d
    replication: 1
    default: yes
  failed_when: false

- name: Add influxdb pacemaker resources
  pcs_resource:
    name: 'influxdb'
    resource_class: 'systemd'
    resource_type: 'systemd:influxdb'
    options: 'op monitor interval=30 --group Trinity-stack'
    state: present
  when: ha|default(False)
  tags: pcs
